# Generated by Django 5.1.7 on 2025-03-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videoproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoproxy',
            options={'verbose_name': 'Published Video', 'verbose_name_plural': 'Published Videos'},
        ),
    ]
